server:
    port: 8084
    servlet:
        context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  file:
    storage-dir: D:/upload
    download-prefix: http://localhost:8888/api/file/media/download